-- PostgreSQL schema for Supabase
-- Run in Supabase SQL Editor

CREATE TABLE author (
    author_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    middle_name VARCHAR(50),
    last_name VARCHAR(50) NOT NULL,
    birth_year INTEGER NOT NULL
);

CREATE TABLE book (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    page_count INTEGER NOT NULL,
    genre VARCHAR(50) NOT NULL,
    publishing_house VARCHAR(100) NOT NULL,
    year_of_release INTEGER NOT NULL,
    isbn VARCHAR(20) NOT NULL UNIQUE,
    author_id INTEGER NOT NULL REFERENCES author(author_id) ON DELETE CASCADE
);

CREATE TABLE "user" (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    dob DATE NOT NULL,
    account_creation_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'book_status') THEN
        CREATE TYPE book_status AS ENUM ('toread','reading','completed','dropped');
    END IF;
END
$$;

CREATE TABLE activity (
    activity_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
    book_id INTEGER NOT NULL REFERENCES book(id) ON DELETE CASCADE,
    book_status book_status NOT NULL,
    progress_completed INTEGER DEFAULT 0,
    start_date DATE,
    end_date DATE
);
